displayName=Tile Overlay Indicators
author=Resh404
support=
description=Tile overlay for NPCs, and players.
tags=indicators,tile, overlay, highlight, draw
plugins=io.leikvolle.tileindicators.ImprovedTileIndicatorsPlugin
version=
build=standard
