displayName=Tile Overlay Indicators
author=LeikvollE, Mark7625, iProdigy, Notloc, Resh404
support=
description=Tile overlay for NPCs, and players.
tags=indicators,tile, overlay, highlight, draw
plugins=io.leikvolle.tileindicators.ImprovedTileIndicatorsPlugin
version=
build=standard
